#!/usr/bin/perl
# goconserver must declare the console-backend capability, or xCAT picks the other backend.
#
# xCAT carries "Requires: xcat-console-backend" because rpm 4.11 on the SLE 12 family rejects a
# boolean dependency outright. Both backends are meant to declare the capability, and goconserver
# is the default everywhere except that family.
#
# goconserver/goconserver.spec is a DUMMY placeholder ("A dummy package", Version 0.0). The spec
# that reaches rpmbuild is generated by goconserver/mockbuild.pl, in two heredocs -- the mock path
# and the prebuilt-payload path. The capability was added to the dummy, so the built rpm never
# carried it: on the sles15 cell zypper satisfied xCAT with conserver-xcat instead, and
# /etc/init.d/conserver stop then hung the run for 24 minutes.
#
# The generated spec is the artifact, so this drives the generator and reads what it wrote.
use strict;
use warnings;
use Test::More;
use File::Basename qw(dirname);

my $root = dirname(__FILE__) . '/..';
my $prog = "$root/goconserver/mockbuild.pl";
open my $fh, '<', $prog or die "cannot read $prog: $!\n";
my $src = do { local $/; <$fh> };
close $fh;

# Every spec the generator can write, taken from the heredocs it feeds to write_file.
my @specs = $src =~ /write_file\(\s*\$spec_file\s*,\s*<<"SPEC"\);\n(.*?)\nSPEC\n/gs;

cmp_ok( scalar(@specs), '>=', 2,
        'mockbuild.pl still writes a spec on both build paths' )
    or die "the spec heredocs in goconserver/mockbuild.pl no longer match -- has it been rewritten?\n";

foreach my $i (0 .. $#specs) {
    like( $specs[$i], qr/^Provides:\s+xcat-console-backend\s*$/m,
          "generated spec $i declares xcat-console-backend" );
    like( $specs[$i], qr/^Name:\s+goconserver\s*$/m,
          "generated spec $i is the goconserver spec" );
}

done_testing();
